# mkdocs.yml
site_name: "GitHub Actions for Data Scientists"
site_author: L Ma
site_description: "Some example of utilizing GitHub Actions"
site_url: "https://emptymalei.github.io/github-actions-for-data-scientists"
repo_url: "https://github.com/emptymalei/github-actions-for-data-scientists"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/github-actions-for-data-scientists"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
      watch:
        - docs
  - mkdocs-jupyter:
      execute: True
      allow_errors: false


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Home": index.md
  - "Demo":
    - "Automate LaTeX Resume": demo/build-latex-resume.md
  - "Notebooks":
    - "Some Charts": notebooks/some_charts.py
