name: datascience
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- jupyter=4.6.1
- matplotlib=3.6.2
- numpy=1.24.1
- pandas=1.5.2
- pip=22.3.1
- pyarrow=10.0.1
- pytest=7.2.0
- python=3.10.17
- s3fs=0.4.0
- seaborn=0.12.2
- pytorch=1.13.1
- torchvision=0.14.1
- torchaudio=0.13.1
