name: Build LaTeX Resume

on:
  push:
    paths:
      - 'automate-latex-resume/*'
      - '.github/workflows/build-resume.yml'
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manually Build Resume'
        default: 'Just want to build it'
        required: false


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # latexmk_use_xelatex: true
          pre_compile: |
            tlmgr update --self
            tlmgr install fontawesome
          working_directory: automate-latex-resume
          root_file: mmayer.tex
      - name: Collect PDF
        run: |
          echo "Copy mmayer.pdf to publish folder"
          mkdir -p publish
          cp automate-latex-resume/mmayer.pdf publish/mmayer.pdf
          mkdir -p docs/assets/files
          cp automate-latex-resume/mmayer.pdf docs/assets/files/mmayer.pdf
      - name: Update Data using Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add docs/assets/files/mmayer.pdf
          git commit -m "Update Resume" || echo "Nothing to update"
          git status
      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          branch: main

      # The following step is publishing the pdf to gh-pages
      # so that one could use a url to access the pdf.
      # we disabled it because we use this action together
      # with mkdocs to generate a website.
      #
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: publish # The folder the action should deploy.
