name: Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/*'
      - 'mkdocs.yml'
      - 'requirements.docs.txt'
      - '.github/workflows/docs-publish.yaml'
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manually Build Docs'
        default: 'Just want to build it'
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - run: pip install -r requirements.docs.txt
      - run: mkdocs gh-deploy --force
