name: Build Personal Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'personalized-docker-image/*'
      - '.github/workflows/personal-docker-image.yml'
  workflow_dispatch:
    inputs:
      name:
        description: 'Build Now'
        required: false
        default: 'I just wanna build it now'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check files
        run: ls -l .
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:personalized-docker-image"
          push: true
          tags: emptymalei/datascience-base:latest